### ISSUE TITLE
NotImplementedError: Layer AddCoords2D has arguments in `__init__` and therefore must override `get_config`.

### ISSUE THREAD

**Issue by rytisss** [mvoelk/keras_layers#1]
Hi, thank you for your implementation. I added AddCoords2D to my model, however, when weights are being saved, it gives an error: 
`NotImplementedError: Layer AddCoords2D has arguments in `__init__` and therefore must override `get_config`.`

**Comment by mvoelk** [comment]
It should be fixed now, but I haven't tested it. Can you confirm?

**Comment by rytisss** [comment]
Thank you! Tested to save and load, everything works!
